name: Events demo
on:
  pull_request:
    types: [opened]
  workflow_dispatch:
  push:
    branches:
      - main #main
      - 'dev-%' # dev-new dev-this-is-new
      - dev
      - 'feat/**' # feat/new
    paths:
      - '.github/workflows/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: output event datums
        run:
          echo " event name is ${{ github.event_name}}"
          echo " event action is ${{ github.event.action}}"
          echo " event sender is ${{ github.event.sender.login}}"
          echo " event repository is ${{ github.event.repository.full_name}}"
          echo " event ref is ${{ github.ref}}"
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci 
      - name: test code
        run: echo " test code"
      - name: build code
        run: echo " build code"
      - name: deploy code
        run: echo " deploying code"


